.TH SHORTCUTTR sc
.SH NAME
Shortcuttr \- a lightweight terminal navigation program
.SH SYNOPSIS
.B sc
.RB [ \-c
.IR --create-shortcut ]
.RB [ \-d
.IR --delete-shortcut ]
.RB [ \-l
.IR --list ]
.RB [ \-fc
.IR  --file-check ]
.RB [ \-fd
.IR --file-delete ]
.RB [ \-fe
.IR --file-edit ]
.RB [ \-ff
.IR --file-flush ]
.RB [ \-fr
.IR --file-restore ]
.RB [ \-fs
.IR --file-show ]
.RB [ \-h
.IR --help ]
.RB [ \--reinstall ]
.RB [ \--uninstall ]

.P
.SH DESCRIPTION
.B Shortcuttr
is a lightweight tool for Bash & zShell compatible with Linux, Unix, & MacOS terminals - reliant on as minimal dependencies as possible - allowing a user to quickly navigate their terminal via persistent Aliases set to Directories without having to pollute their .rc files or manually set aliases every session!

.SH Usage
.TP
Usage: sc <Alias> || sc <Flag> || sc <Flag> <Alias>

.SH FLAGS
.TP
.B \-c
Creates the Alias to the current Directory of the User - e.g: sc -c <Alias>

.SH
.TP
.B \-d
Deletes an Alias set in the Database based-off the entered Alias - e.g: sc -d <Alias>
.SH
.TP
.B \-l
Lists all saved Shortcuts allowing the User to change the directory based-off the corresponding number entered in the terminal

.SH
.TP
.B \-fc
Checks for the existence of the Database file "shortcuts.txt", and creates it if non-existent

.SH
.TP
.B \-fd
Deletes the whole Database should the User wish so

.SH
.TP
.B \-fe
Enables the User to manually edit the Database to fix any mistakes without having to flush or delete their other Alias'

.SH
.TP
.B \-ff
Deletes all the previously-set Alias' so that the User may begin again

.SH 
.TP
.B \-fr
Restores the Database from an automatic backup 

.SH
.TP
.B \-fs
Displays the Database in the CLI for the User so they can easily look at their Alias

.SH
.TP
.B \<Alias>
Brings the User to the corresponding directory set by the User

.SH
.TP
.B \--help
Brings up a summarized User-Manual to help the stupid

.SH
.TP
.B \--reinstall
Reinstalls the script again by calling the install script

.SH
.TP
.B \--uninstall
Uninstalls the program, removing the Alias' set in the .rc files, and removing the Man Page, as well as Deleting the Program Folder

.SH AUTHOR
.B Finn Mallon
.SH COPYRIGHT
.B Copyright@2024 Finn Mallon - this script is protected by Law; any unauthorized use is punishable by death by the US Army whom I maintain a strong friendship with!
